# SHISHU MUDRA DATASOURCE
datasource.lendperfect.url: jdbc:oracle:thin:@172.31.12.5:1803:losstpdb
datasource.lendperfect.username:IOB_ONL_PAPL_PROD
datasource.lendperfect.password:iobpapl#123
datasource.lendperfect.driverClassName: oracle.jdbc.driver.OracleDriver
datasource.lendperfect.hibernate.hbm2ddl.method: validate


datasource.lendperfect.hibernate.show_sql: true
datasource.lendperfect.hibernate.format_sql: true

#Using Hibernate Dialect
#datasource.lendperfect.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
#Custom Hibernate Dialect
datasource.lendperfect.hibernate.dialect: com.sai.lendperfect.controller.CustomDialectOracle
#datasource.lendperfect.hibernate.dialect: org.hibernate.dialect.Oracle8iDialect

datasource.lendperfect.type: prod
datasource.lendperfect.jndi-name: java:/jdbc/LSDS
datasource.lendperfect.jndi-nametwo: java:/jdbc/LSDSTWO
datasource.lendperfect.jndi-namethree: java:/jdbc/LSDSTHREE


#lapsdbsms.datasource.url: jdbc:oracle:thin:@192.168.0.145:1521:DBORCL19C
#lapsdbsms.datasource.username:training
#lapsdbsms.datasource.password:training
#lapsdbsms.datasource.driverClassName: oracle.jdbc.driver.OracleDriver
#lapsdbsms.datasource.hibernate.hbm2ddl.method: validate
#lapsdbsms.datasource.hibernate.show_sql: false
#lapsdbsms.datasource.hibernate.format_sql: false

##YES BANK DATASOURCE
yesbank.datasource.url: jdbc:oracle:thin:@172.31.12.5:1803:losstpdb
yesbank.datasource.username:LOS_MIS_DB_PROD
yesbank.datasource.password:losmis#123
yesbank.datasource.driverClassName: oracle.jdbc.driver.OracleDriver
yesbank.datasource.hibernate.hbm2ddl.method: validate
yesbank.datasource.hibernate.show_sql: true
yesbank.datasource.hibernate.format_sql: false


#SERVER DETAILS
server.port:9090
server.contextPath:/lendperfect
server.error.whitelabel.enabled = false
server.session.timeout = 1800

sms.enable: Y
email.enable: N
email.branch : N
email.cc: mohan.r@sysarcinfomatix.com
email.environment:test

server.servlet.context-path=/lendperfect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.ftl
spring.main.allow-circular-references=true


cbs.accOpenDate:Y
cbs.staffInd:N
bank.encdeckey:f72a00e8362a4f2aa29c5e9ac0c70159
cbs.chkPrvLoan:N
cbs.occupationCode:1000
cbs.chkOccupation:Y
chkIpAddress:N

liveLinessModal:N
liveLinessReject:Y
redirectUrl:https://stg.nesl.co.in/DDE_Response/response.jsp
#redirectUrl:http://192.168.0.215:8080/lendperfect/shishulanding
redirectFlag:N
#redirectUrl:&redirect_uri=https://www.google.com
livelinessUrl:&redirect_uri=http://192.168.0.161:8080/lendperfect/shishulanding

defaulter.enable:N
defaulter.enable.ab:N
dbLinkLive:Y

sms.deptId:SHISHU

karzaGst:Y
cors.url =*
#cors.url = http://192.168.0.244:4200/landing
#eSign.dscofscrty = Security Hypothecation of stock, book debts & assets created / purchased out of Bank finance
esigneddocument.uploadpath=/LENDperfect/ONLINE_PAPL_UAT/esigneddocument
esigndocument.uploadpath=/LENDperfect/ONLINE_PAPL_UAT/esigndocument
eSign.dscofscrty = Security
eSign.asstyp = Movable
eSign.typofchrg = Hypothecation
#eSign.keyfilelocation=/LENDperfect/ONLINE/ONLINE_PAPL_UAT/iob_pfx/iobcert.pfx
eSign.keyfilelocation=/LENDPERFECT/PAPL/Nesl/4294957.pfx
eSign.pwd=Password#1
eSign.keyfilelocationNesl=/LENDPERFECT/PAPL/Nesl/4294957.pfx
eSign.pwdNesl=Password#1
eSign.NeslrequestURL=https://iu.nesl.co.in/DDE_IU_Registration/IUREG
eSign.NeslresponseURL=https://iu.nesl.co.in/DDE_Response/response.jsp
eSign.NeslProxyflag = FALSE
eSign.NeslProxyAddress = 192.168.0.49
eSign.NeslProxyPort = 3030
eSign.NeslclientID = IOBSTP
eSign.apiKey = KGdGlQ4Fg0i7m4XyDaCT
eSign.authorization =Basic SU9CU1RQOlY5cmRReWN4
eSign.api = Y
document.uploadpath = D:/UCO/LENDPerfect/Shisu/

eSign.response.privateKey = MIIUogIBAzCCFFwGCSqGSIb3DQEHAaCCFE0EghRJMIIURTCCBWoGCSqGSIb3DQEHAaCCBVsEggVXMIIFUzCCBU8GCyqGSIb3DQEMCgECoIIE+jCCBPYwKAYKKoZIhvcNAQwBAzAaBBTQL8MyY8x7yCmfJNzFuNmESVhDpgICBAAEggTICT/bWm6P7NXCslvgSfgdrzltIP3VbatJhvNAD0KeklqpTgdExQ0xsGwRXRxA6pz/w+5+qqaZGKEZKwlOgsBQ0o/dxQFLEoLc58HLKe0oxPovdzjLtjS9DLNDMl/3uSnCrWQHK/6Uu5792AHrTLVmHCamCaZDusw0YlhF7v2ApMzi4IdcSkZvxrL6wAq2EpVtSX5wjtkpBXp8VzKKtTAvBbyd1DQeb+ueR+NTDiuaL+LYEVO8gQiSb5SPYuBpwSyqVxguQ4xQQ4cRaxyrlrnpAgIEUiKDmMiH6Jhu8zSyKgRgU5QJvgbcmPwRXIr7Q87o1rfkIvu48RafAsFEqnnV1LZAtLI3GK21uJLCHzF8toGJDgIvxBE2SDpUWuvW4qAoairFUgtbvuJhyeMdV7Vp3cioy1Ogo4aa5tQ68PyvnhHvJHSOcIzBWB3/NPNaPekshL73fp7GdCHuqpLapohsWe6zUBUUsHGjfoXSiL2IGQesDBXbJ5xa71Bd9KkUl4/xkSeCkQxL0Ae/H6+H8DBkZh6AQoaFlT8Gsa8w54XFmgy0rwlIw2eGZagC4yb6A0ohisACFlgFHptgi7bZNloT04ixXgYtTxExId463zZPSuckiNrp3jhrl2Ni81otSIYz8PhGxyTG6NUgGxmRRPMSGWsZLjGm6HQtR39R9Y66zxDozx195KExTDlJkdEWc13ZjD0nV9t4l1LvcpNFkaElrlPfMB3QP1yd4fdMbBFd4JN/g5GuRAcFaazZRi2dGsluzsiHaocw1ejMTNA+Dhc/MVMdxL78YFKogPhiJ1UaQ5PNzWiAh49T3BbCb6KPdcg9Dw0nG0iEZn9F+RQzx95tbCHfGbWd+vKgksR+XRa9yn2Lx6HVI1+azLZj2lUmE3yZQ/Ju6RKWDfv0utNGTcw+NZuSgGJxw9tGyCChwt08r/uW2oUr+ZdrvI4v4ZSLVGcTWDj/wYXy/QG8APQR3r7UDWnZcoBgzgWSSAr2vmVmNm9u7rbDMS/WkIkbbDtQ6LSgXaBNhl2icaW2Q12iiU35PRTolrMRlA+oAnjatSomjDrsG7bVYoOtfNUm5YPvXY+adaVfN1PmpaFwRIvbamsZchn8vFT7Ew+wHblt4TvRs9T8s6KLmIkn+QWfdSt0YXpdxkEk+/7GHbK0+riPpDzPEoHV0Iyanl3rWvTveHAsL8W9E0n2PGNPz9rZZpbWICQv12vjOXomEjG5bgJ0o5LeZuJslyHs9Aw7VLEnN0k7//+yneiq3eJTZPm0oP6mmZRQcPMjHggm72APH3NG9Y2Cc/sMuM95hISs2MjqLlCN4T4jzuBjTmYheCRwO2WdHyh8s6GzVNpKC50jE/GwKdFXq3YM+jrjcG1MXn4frXRrU2MUELFBI6e4nrVlCVfNzbiG0DuewPdaj4JohxrFFIjYePqBj5QW+amVQITfocohKcIxXYidqvo+9jVY+3qSUe8rn0iJAcy/FHbL18c/ObNAGdOD054v+L4H1NEWwg/srQTHHAMOQIXUV5PuoqN5izjvxGu7Y02wHPRCyHqggYFUvBtXMBINh++PcdQ+IzoLqXM5dbPXa1ga4Hf6frpXUGrDiG+hW1+jb0yF9BSQBM3RpskJvPgwQit7MUIwHQYJKoZIhvcNAQkUMRAeDgBtAGEAZABoAHUAIABsMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE2NTcyNzY2NjcyMDUwgg7TBgkqhkiG9w0BBwaggg7EMIIOwAIBADCCDrkGCSqGSIb3DQEHATAoBgoqhkiG9w0BDAEGMBoEFPoufIKZrr+5ZwCziFlix+hUldmEAgIEAICCDoDcavcpjm/D4u5dH7JTnojOsXJ8HfPpOlhy66k9+6YNyVcuMw4WU5Jc7BZjJaULdMKLhAIm08zF9x8rovj7Hn1ilzv1Ai2OfEhIKNe1qC4PW3I5IoOJZ6jC5NOgM8pBM00652e1ZPhsMHgm8rRzSUC1dL6sRjOx4aId5Hxe6O5MMDpyuTNvPMfMcP+XtrgrS3w9mpIDmx7x/Gw/6kZmCNbiiB9rfq4huqInoOGpFjy4NYrVJutXcPk1P38qwHRVtx1Q7QJ0JqdP/PH/kzhUhZRhTpFEww/Lt8LIamd7WpBQ1pupg7W4FWuH+lcEwr9Y62//zJKyyEONczgXnluYD8R1KzVSjIuWZZOxA4V/WKbuR1tLsV3oT2DvEVXVrsvtdpHj32kzRQAeP2AenZeU7P1bSGFPY+3c+fUp48tz9yOuKUVyqAC55dC6l5KhzzQAJ6rvoFRS/2yoXE5PfVXzsLpo96LbVvZiHD27CC/O4SO9JWrXF5qYHgPwCsYynbofBneWVpfZGxhFCP+OATXsEBBImbSjhGBYJnQCTJLSqbbok/FDbtehqQCz/aCkGRLPkM/upp21wAKCjFmKnZ+S6IXcPcQxDmtIxB40ffywOFpUyUKDu7X/66SrC+c2V6wfCS39KURINjZbEKXaYa0xrOl4XLtmoiu2l3/mhPh3UMJdpIynLBSFVC1jTzFgoN9TXNDAGWLo7mtT2xqix00wzCZbyG9WrS3jMglIMMey26zleJ+FfeYxbDFOmOjrWYdF/AiyHcuHddDtOSlTZvkHvfSCD5Gt/DBx9SaiR4nNn5IO/cRQRMHj0dznZ2TlciOxFwdbH12QmOU0Sfhk6T373dF8dcyzlAo7cNxdOpzTXa4FOwVzRDQNOinvFGTWE/p3KJVpojOAOf8Tn06TYiICLptVE4hTHg6EyFSBrKolnreAEfJeiK4Rv3UNxKgox8c+j1x19hTxVhT9H7RDEmfyK10hvGd1NP4r6W174oOb+SsavPn4jkFLCbJy+Z148K3e0+eSQ+TQtNHQ1IaMhgjXoC4vEq1zRp+nvz6Q61eGzdZtyoDe0B7zLCfUINia6e3qtnMcBNBUi0JJOt7KgAb1tJ1MDTBYpBTpl5H6zzxPgPReVmXvjzARs2ZPJZ4QqDfAFd7wZEv6cSXtxZ9dX3I8wL9F5kCulrPraberigQW9LB3FSZtTNdxPeeAehUocrLzoJiYhC1DQ4kU5Gq0YfVpoKI2+kMnj3ZE/ehd6+IlUG6tn3PQKGFWc5gs12rXgGLY1MxY54yJEiyPdYZ6t5VpmEk45GXMZ96dbXUhrJ5LiAiCcZrejuufVEy2UMXE69/cR5F8iYznFAiLl0MCRrQMP8mF3fXvfIYNh1K9xBX72gnlxWKG1fLbLHeH3oyEmMr4LsqcsVSkymtkYM2IaasO7X8yGuQChOYbh6GnA2dL0J0s5FWi1kkcgU6o4/6Ar4MR+VchZijuZ/Bf0dAJNUaP2nSZSLZEDSEOi1kIWLmftlPbv3FwyE5OrAcCuhtTkNbqcyNhchRj8M6wWZQOfjIeWMwJc7rgjSWXiRKd1hIMt7ztgG4tDGBF+RO6/BE3HBpiu+DqYOeGwjHMfM09NLhYEZaWrVCw9l61E08HpVnBvfuCj66qHui0n2+QVd3eTlH0XK1fTsUuBMiCrCuy/C5XYgkoi7aUMLkq59Sfcc3PXjJZIJUscJ48wGIKP5TVrhPfz1tgvvZIUGpJv5gINJjUPIvUV7vr9DRBTc9kVIn14+Z1Xx8AOWR4Qm9Pfs7CwsOVh3PGVENB+dpx1Acl9xgZvpJwEbIOQil0VEeXfUrUcxCGtEp3svnsQtBqJXnDSHkxQrAQAnN/okkP0NLmvwvHuXq1wdyObhrDZwwObLU7CXFR7cPDGGO3R5P5BBjC02L+eb56ojfnz4xeSqZHSmNhmxQMru5emN7rH0+BlEid+1vpVaQ8CPnSDet7c18mWsO7QGlpSfPapsh/ce8bIbgI8twOGaiSZJhfHguRN+ivrAyTOM6c4TPqSpGjY0vaWaHpCq/g7mE3EKlyNKUI0yS4VHHRd/fbjtJzbX1SGWtd205adv3RpkiQdYnvfWllSKvJnYQfZE48HELQ+FohERNTxsf8+/nJJKEpkYEPpApoZBuK3g/Jf2NHemiJMDVo0sSeGsUVskCKeVCsw8TgLjhAWhvcPijenFi4Cw9uhHSS70Lv2YqtxI4ejovHxaI2vsndQzsg7dzhLUSWguSYiMMm6segmUQnX0IY24byztjLG1ZQECnY3UhtM+SnlzEn4rBYrpBzqBHqVmcwlDeCFj5xd/9QfFC+Id8tq8wSb2Ln1SNNxQu+xAY+s9dnOig+KXhAI6vaYbSDdENnkZXXBNEBIPxCgcxgVy0LNCWzmLpPwwsmnQ1mRw5nw2EjFXACuK72NraGFMyCgMbuMgnyvwZA/MI5XnXmBwxjcbq4cKNBBB3KMT57hMgoHImirE1N9tSiqGP1v7tnMrtvDA1koMvwiQ98riTyXX58/LrQfyrxiqpb8puOUHgqZOCFKWCO1rYxJabjqyCUzs/Ff3P1nJJugYavXr476XGVZ7LORDeFMq74F1CEZYvoweEIuqDEBzfn8mHtLnMDb3rh8+fPOrOn6Wa+auSzTWd1OQkHSsg2t8UFlssTlGVXnV2aCAxNxilM7ASPOeIJjtjgNkZLBBoj8vh/vw3BcnvxMOJm4fTYu6K1ymFSjmubycZparkdaWGSiDyjomkOhNhpi8qxfFLCpiYI6N9rkzdmhTYO+gdxTMUIeYNXW9o+iCK+rCb7NA2Ej7DnhRlbo00OOR4EIrR8dM5QPn1Oyr99VbZ+K7O4nMDUj8rcmhXCLUcpuQQdygYUPBpO1jIsJrZpOZ9MajumevGaSxzStOLfht+wfNe+PQ/Y5Oyqu98qBwskFjFfKhpFHveYs5ufSVc/J+PEgTGMVhYfSm7tLITqaLpQJJRXtqqFX459SULo87sg71BI5cMeE5JLX2tOHT1dp2nIP5rvTWUOoXzGm8PehyqayrMf2yc6LbFxe+KDxRie6zzLrEo9uSWcvtF1j4qSTnhnB4EzY3mEbGD8vdqJItTtvdICV+/iyH+wrDhNrALY/50sw1A1Z0d8i0QACXyR8V0BRx5C+Jyz1Q8nrFoVP1sYf1lJtl0+yCnUTXh3fk0iqeYoKQ+E/8zWQbEfUra5f5T5sHpay2lL9D/6JdGYrv44tpdGg2CdrE9VCPS6MuSW6YkEtM/ngenynPsdehVhVKgXZ6w5mPY/Pc78oToo8IGydw05NOIwbjnyop5WIAJyiK0CWbYjQDq1xXkMGYl/99Oxj7N+fqKloitgy+VYcN9ugSyEyXgqYSeG44r17oa2o+wK1SK+HkCjft4/OSRIxLldzdHnZBDxBqSJmqm2wYadvwT+UCOCY9wD001oDxNg+UPWG9LD88j5J0i0Ut/nHFMQwuQbTWJJg1PhRpG2jcdjp8FmKfu2/xzJuUgv5mRvducjtxdSnVlkzYRMKBzY/+HgNl8vqV3GMwHJVy/Zikj+NKfcUuBmjY8DArf+SMSpSzMYXQ5mXjcOPBWgkhSBxrXNuQD64DjimseN7gdzVGMKRcq/9YyRS62nr48Rl6S1x+iii2EXqrdv32H7lohpWLvRLPydAfvU03pcL2inJf97CSguLGlqpA7v5rmIe7JDxglMD5uIGh02HuSgRoFhYZOZknb9JtorPSvziwbe/oo/OokjXIXlYTP7cn0CUWc+7W+FSp8rcAkzs72rATjOaC/4f6hdt/F2hQ8AdkUOuOERQ8SKMBMyqzug9aGYlY5gsoT0QXGUU8KMKKgOAzeYfp0HbpmgBIGP92i/b7sIlrWty7u6Lfhh7RGPxh3TUnx1ndiL7eZ02mO8MwGq9sZL+IJVT49DhSwd6FXht4NfoRmAH6JWeKq6V2L44xzVUY/59jnlKbrUqa8TP0eNySTaIHytTBHGkCJcUM+65hnO3ghX4BCvETGvttww73vlNeCOmzHCbtTgqnMK+bSY4122YUfAh9xHhOBfvKzaMmjLFqnJkhtR1jSgzwRez8nm58MIJbkHJGVuJtOYmGEpvXsgJOvtUWf7BvPfLkm6eAi8BGsH67cNR2ZcrqdBPXlpDOWBTpRMTbjr76HzGTNx2/A4i8DioLawfbFlO/HKMCAD2lu8WPScCEQoitWAQxMgw6MNVniYxw91HNezoCt6yND+aHX167bCGI5kU4uQ60iMpMfI0oUtPflk0yxPu2eU1DWzcAIzvOPGrlXJlC7IeMDSPEjXE6omkzJYP7Cv1TUG4XR+OwHurMKr5IsPlcVeWN4mSeZu3M/QT1UzMBgkDLyySaN5lptdLWmb6rWB1XPIQRAVMygTh5gxXZ53PbQBIo7HWXsZIBvOSCqPMERyok7E0jJ6BRHHHkIg8jgKB7HnYDM7wVp+CDU4h2jfkJzzgwrz//EZShFfP5YsPnvbQqSWF1ofCpMeyVl7FnbPrwrWP4HOBoOLcG15z9lJIzCyv54FOBTYihTVIa95GItTwwTkd9m3EJ7MOKNNRilZ/aM2TUMGQk0POvs+ha/aB2gJz+UVUxIl8ePjZHY4yRrs4zF6H5nV55jMH8vE/z9kZK+nMKTcfDwETeeUY35mUFGgi2qo8SwHq+QcMWtzf3baG8JVbXrEFbYt2rg/eV3usL4hyzcdDuPx/0D6MhXQSdDqK5SOe45rOs9v9gpI0SI3iRp4u1TnrydSv8vdm8hEaKMq56wzIVKFLkI+AxToGRBmeSdK1IXTfb7KbLEhakMSiDOlDd4L+PEpyYqXjSSsVOjdaJ/ZFGGcqoCWnYZKp3Xdr2TNq8sfGGts2x6m2T7bg+PW8molmn87cQwga3oQO5OnDtZ/W7l90RNufbkU9Eik+tNnPMtxIB9PEDSIDQ+Qvsdh/Y3NYSCWyilSMD0wITAJBgUrDgMCGgUABBTAtWEpZ+V2GXB//cVwVWBvzKgACwQUuUSHl80X4R87mitlQeHm1I49ZCsCAgQA
eSign.response.pwd =Password#1


sms.enableforliveleness:N
mudradedupe.enable:N
outstanding.enable:Y

solidupdate.enable:N
#logging.level.org.springframework.web=DEBUG

server.compression.enabled: true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg
server.compression.min-response-size=1024

#CBS Server
CBSserver.ip:10.100.7.5
CBSserver.port:8881

environment:UAT


pfx.filelocation=/LENDperfect/ONLINE/ONLINE_PAPL_UAT/pfx_15032023/UCOSTP.pfx
pfx.password=AE567@#XA
emptypdf.location=D:/test.pdf
signedpdf.location=D:/PFX_IB_SIGN/test1.pdf
signedimg.location=D:/PFX_IB_SIGN/GeeksforGeeks.png

Debit.public.keyfilelocation=/LENDperfect/Selfsigned/SANDBOX.crt
Debit.private.keyfilelocation=/LENDperfect/Selfsigned/iob_private.key

customerConsent="Test"
sec=rmklopkjuranjkislasdfrewsjfdrtyu
spring.main.allow-circular-references:true
server.servlet.context-path:/lendperfect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.ftl
server.servlet.session.tracking-modes=cookie
spring.main.allow-bean-definition-overriding=true