datasource.lendperfect.url: jdbc:oracle:thin:@172.31.12.5:1803:losstpdb
datasource.lendperfect.username:IOB_ONL_KCC_PROD
datasource.lendperfect.password:iobkcc#123
datasource.lendperfect.driverClassName: oracle.jdbc.driver.OracleDriver
datasource.lendperfect.hibernate.hbm2ddl.method: validate
datasource.lendperfect.hibernate.show_sql: true
datasource.lendperfect.hibernate.format_sql: true
datasource.lendperfect.hibernate.dialect: com.sai.lendperfect.controller.CustomDialectOracle

datasource.lendperfect.type: prod
datasource.lendperfect.jndi-name: java:/jdbc/LSDS
datasource.lendperfect.jndi-nametwo: java:/jdbc/LSDSTWO

yesbank.datasource.url: jdbc:oracle:thin:@172.31.12.5:1803:losstpdb
yesbank.datasource.username:IOB_MIS_DB_PROD
yesbank.datasource.password:iobmis#123
yesbank.datasource.driverClassName: oracle.jdbc.driver.OracleDriver
yesbank.datasource.hibernate.hbm2ddl.method: validate
yesbank.datasource.hibernate.show_sql: true
yesbank.datasource.hibernate.format_sql: false 

#SERVER DETAILS
server.port:1111
server.contextPath:/lendperfect
server.error.whitelabel.enabled = false
server.session.timeout = 1800

sms.enable: Y
email.enable: N
email.branch : N
email.cc: mohan.r@sysarcinfomatix.com
email.environment:prod

esigndocument.uploadpath=C:/ESignDocuments

cbs.accOpenDate:Y
cbs.staffInd:N
bank.encdeckey:f72a00e8362a4f2aa29c5e9ac0c70159
cbs.chkPrvLoan:N
cbs.occupationCode:1000
cbs.chkOccupation:Y
chkIpAddress:N

liveLinessModal:N
liveLinessReject:Y
redirectUrl:https://stg.nesl.co.in/DDE_Response/response.jsp
redirectFlag:N
livelinessUrl:&redirect_uri=http://192.168.0.161:8080/lendperfect/shishulanding

defaulter.enable:N
defaulter.enable.ab:N
dbLinkLive:Y

sms.deptId:SHISHU

karzaGst:Y

cors.url = *

eSign.dscofscrty = Security
eSign.asstyp = Movable
eSign.typofchrg = Hypothecation
eSign.keyfilelocation = D:/Mohan Documents/Bank Documents/Bank Documents/Nesl Pfx/UCO Shishu Mudra/UCOSTP.pfx

eSign.pwd=12345

eSign.NeslrequestURL = https://stg.nesl.co.in/DDE_IU_Registration_V3/IUREG


eSign.NeslresponseURL=https://stg.nesl.co.in/DDE_Response/response.jsp
eSign.NeslProxyflag = FALSE
eSign.NeslProxyAddress = 192.168.0.49
eSign.NeslProxyPort = 3030

eSign.NeslclientID = UCOSTP
eSign.apiKey = idJWlgXuxlmBHIaCZVki
eSign.apiKey = c30lt5YFW81cru1ozQGb
#eSign.authorization = Basic VUJJU006TlpnQ3pkQ2U=
eSign.authorization = Basic VUNPU1RQOjY1TEJ6SFR1
eSign.api = Y
#document.uploadpath = G:\\UBI\\LENDPerfect\\Shisu\\
document.uploadpath = D:/UCO/LENDPerfect/Shisu/

sms.enableforliveleness:N
mudradedupe.enable:N
outstanding.enable:Y

#esigneddocument.uploadpath=C:\\E-Sign Signed Documents
esigneddocument.uploadpath=C:/ESignSignedDocuments
solidupdate.enable:N
#logging.level.org.springframework.web=DEBUG

server.compression.enabled: true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg
server.compression.min-response-size=1024

#CBS Server
CBSserver.ip:10.100.7.5
CBSserver.port:8881

environment:PROD
sec=rmklopkjuranjkislasdfrewsjfdrtyu
spring.main.allow-circular-references:true
server.servlet.context-path:/lendperfect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.ftl
server.servlet.session.tracking-modes=cookie
spring.main.allow-bean-definition-overriding=true
iv=46811b9f06f94e2d222a82c418b44678
 
