# mod_proxy_balancer should be disabled when mod_cluster is used
LoadModule proxy_cluster_module /LENDperfect_CRM/WEB_SERVER/APACHE_CM/httpd/modules/mod_proxy_cluster.so
LoadModule cluster_slotmem_module /LENDperfect_CRM/WEB_SERVER/APACHE_CM/httpd/modules/mod_cluster_slotmem.so
LoadModule manager_module /LENDperfect_CRM/WEB_SERVER/APACHE_CM/httpd/modules/mod_manager.so
LoadModule advertise_module /LENDperfect_CRM/WEB_SERVER/APACHE_CM/httpd/modules/mod_advertise.so

MemManagerFile /LENDperfect_CRM/WEB_SERVER/APACHE_CM/httpd/cache/mod_proxy_cluster

<IfModule manager_module>
  Listen 172.31.4.97:1801
# SecStatusEngine On
  SSLProxyEngine On
  SSLProxyVerify None
  SSLProxyCheckPeerCN Off
  SSLProxyCheckPeerName Off
  ProxyPreserveHost On
  ProxyRequests Off
  SSLProxyProtocol -all +TLSv1.2
  SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256
  Maxnode 50
  Maxhost 100
  MaxContext 100
  managerBalancerName losdhana
  LogLevel error
<VirtualHost 172.31.4.97:1801>
    DirectoryIndex disabled
<Directory />
    Require all granted
</Directory>
    ServerAdvertise on
   #EnableMCMPReceive
    AdvertiseFrequency 50
  SSLEngine On
  SSLVerifyDepth 10
  SSLProxyProtocol -all +TLSv1.2
#  SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-CHACHA20-POLY1305-SHA256,ECDH-RSA-AES128-GCM-SHA256ECDH-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305-SHA256,ECDH-ECDSA-AES128-GCM-SHA256,ECDH-ECDSA-AES256-GCM-SHA384
  SSLCertificateFile /LENDperfect_CRM/SSL_CERT/ARUN_SSL/IOB_CERT.crt
  SSLCertificateKeyFile /LENDperfect_CRM/SSL_CERT/ARUN_SSL/IOB_KEY.key
  SSLCACertificateFile /LENDperfect_CRM/SSL_CERT/ARUN_SSL/CAcert.cer
 #EnableMCPMReceive
<Location /mod_cluster>
      EnableMCMPReceive
      SetHandler mod_cluster-manager
 
      Require all granted
</Location>
##############################HostHeader Attack Harding####################################
#RewriteEngine On
#RewriteCond %{HTTP_HOST} !^(https://crditmonitoring.iob.in:443|crditmonitoring.iob.in:443)$ [NC]
#RewriteRule .* - [F,R=403]
</VirtualHost>
</IfModule>
