# IOB_CreditMonitoring  DATASOURCE
datasource.creditmonitoring.url: jdbc:oracle:thin:@172.31.12.134:1803:CRMD
datasource.creditmonitoring.username:IOB_CreditMonitoring
datasource.creditmonitoring.password:H@ppy!J@n2026
datasource.creditmonitoring.driverClassName: oracle.jdbc.driver.OracleDriver
datasource.creditmonitoring.hibernate.hbm2ddl.method: validate
datasource.creditmonitoring.hibernate.show_sql: true
datasource.creditmonitoring.hibernate.format_sql: false
spring.main.allow-bean-definition-overriding=true
datasource.creditmonitoring.hibernate.dialect: com.sai.lendperfect.controller.CustomDialectOracle
datasource.creditmonitoring.type: dev
datasource.creditmonitoring.jndi-name: java:/jdbc/lpDS0

#LOSDb
datasource1.lendperfect.url: jdbc:oracle:thin:@172.28.248.6:1803:LENDPROD
datasource1.lendperfect.username:IOB_LEND_PROD
datasource1.lendperfect.password:laps
datasource1.lendperfect.driverClassName: oracle.jdbc.driver.OracleDriver
datasource1.lendperfect.hibernate.hbm2ddl.method: validate
datasource1.lendperfect.hibernate.show_sql: true
datasource1.lendperfect.hibernate.format_sql: false
spring.main.allow-bean-definition-overriding=true
datasource1.lendperfect.type: retail
datasource1.lendperfect.jndi-name2: java:/jdbc/lpDS1

#VC_CLC-2.7.3 Starts
#Spring level properties
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.ftl
spring.main.allow-circular-references=true

#Server level properties
server.servlet.context-path=/lendperfect
server.servlet.session.tracking-modes=cookie
server.error.whitelabel.enabled=false
#VC_CLC-2.7.3 Ends

#SERVER DETAILS
server.port:9050
server.contextPath:/lendperfect
server.error.whitelabel.enabled = false
server.session.timeout = 1800
server.session.cookie.max-age= 3600
server.session.cookie.name= MONITORSESSIONID
server.session.cookie.secure= false
server.session.cookie.http-only= false
server.session.cookie.path=/


defaulter.enable:N
defaulter.enable.ab:N
dbLinkLive:Y

#cors.url = http://192.168.0.79:4500
#org.url= http://192.168.0.79:4500

cors.url = *
org.url= *
socketServer.ip=10.100.7.5
socketServer.port=7771

#logging.level.org.springframework.web=DEBUG

server.compression.enabled: true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg
server.compression.min-response-size=1024

spring.servlet.mutlipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

encryption.enable = true
